# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-21 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
