# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-02-22 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_remove_book_is_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='wishlist_logo',
        ),
    ]
